apiVersion: v1
kind: Service
metadata:
  name: gocounter
  labels:
    name: gocounter
spec:
  ports: 
  - targetPort: gocounterport
    port: 8080 
    nodePort: $NODE_PORT
  type: NodePort
  selector:
    app: gocounter
